{% set name = "varname" %}
{% set version = "0.13.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/varname-{{ version }}.tar.gz
  sha256: fcaee413d28dc84301e5b2c6383b8c8b5d15eccc2218b5a1d1c50f21df024e2c

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=0.12
    - python >=3.8,<4.0
  run:
    - python >=3.8,<4.0
    - asttokens >=2.0.0,<3.0.0
    - executing >=2.0,<3.0


test:
  imports:
    - varname
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pwwang/python-varname
  summary: Dark magics about variable names in python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
