{% set name = "varname" %}
{% set version = "0.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/varname-{{ version }}.tar.gz
  sha256: 35384677e083202a60a8ed18ff336020e5d017cf8dc1691d09485539c45aa38b

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - executing >=2.1.0,<3.0.0


test:
  imports:
    - varname
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pwwang/python-varname
  summary: Dark magics about variable names in python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
