{% set name = "varname" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/varname-{{ version }}.tar.gz
  sha256: 671a85ba6888099aad928dac2341a3566f27b235029e775dcd6c662e744e1ce5

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=0.12
    - python >=3.6,<4.0
  run:
    - asttokens >=2.0.0,<3.0.0
    - executing >=1.0,<2.0
    - pure_eval <1.0.0
    - python >=3.6,<4.0

test:
  imports:
    - varname
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pwwang/python-varname
  summary: Dark magics about variable names in python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
