schema_version: 1

context:
  name: varname
  version: 0.15.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/varname-${{ version }}.tar.gz
  sha256: 86e66d59adf97ed301169ab0cb9b33a2f08f3184cd9c3b14901a09d1972dbfee

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - executing >=2.1.0,<3.0.0
    - typing_extensions >=4.13.0,<5.0.0

tests:
  - python:
      imports:
        - varname
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Dark magics about variable names in python.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/pwwang/python-varname

extra:
  recipe-maintainers:
    - thewchan
